version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run: 
          command: | 
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.14.37

            eval $(aws ecr get-login --region eu-west-2 --no-include-email)

            docker build -t vote .
            docker tag result:latest 122275815213.dkr.ecr.eu-west-2.amazonaws.com/vote:latest
            docker push 122275815213.dkr.ecr.eu-west-2.amazonaws.com/vote:latest